### ISSUE TITLE
During update: error[E0658]: `cfg(doctest)` is experimental and subject to change

### ISSUE THREAD

**Issue by gaia** [iqlusioninc/tmkms#84]
![image](https://user-images.githubusercontent.com/87547/85187106-063dd780-b252-11ea-80fc-d5f086c2aa88.png)

when updating from 0.7.2 to 0.7.3 via `cargo install-update -a`

fixed by `rustup update` to `rust version 1.44.1 (c7087fe00 2020-06-17)`
